/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MemeCoinMarketplace {
  export type MarketItemStruct = {
    marketItemId: BigNumberish;
    amount: BigNumberish;
    tokenAddress: AddressLike;
    seller: AddressLike;
    buyer: AddressLike;
    price: BigNumberish;
    sold: boolean;
    canceled: boolean;
  };

  export type MarketItemStructOutput = [
    marketItemId: bigint,
    amount: bigint,
    tokenAddress: string,
    seller: string,
    buyer: string,
    price: bigint,
    sold: boolean,
    canceled: boolean
  ] & {
    marketItemId: bigint;
    amount: bigint;
    tokenAddress: string;
    seller: string;
    buyer: string;
    price: bigint;
    sold: boolean;
    canceled: boolean;
  };
}

export interface MemeCoinMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelMarketItem"
      | "createMarketForSale"
      | "createMarketItem"
      | "fetchAvailableMarketItems"
      | "getListingFees"
      | "marketItemIdToMarketItem"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cancelMarketItem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarketForSale",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarketItem",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchAvailableMarketItems",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getListingFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketItemIdToMarketItem",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelMarketItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarketForSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarketItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchAvailableMarketItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getListingFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketItemIdToMarketItem",
    data: BytesLike
  ): Result;
}

export interface MemeCoinMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): MemeCoinMarketplace;
  waitForDeployment(): Promise<this>;

  interface: MemeCoinMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelMarketItem: TypedContractMethod<
    [marketItemId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createMarketForSale: TypedContractMethod<
    [marketItemId: BigNumberish],
    [void],
    "payable"
  >;

  createMarketItem: TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish, price: BigNumberish],
    [void],
    "payable"
  >;

  fetchAvailableMarketItems: TypedContractMethod<
    [],
    [MemeCoinMarketplace.MarketItemStructOutput[]],
    "view"
  >;

  getListingFees: TypedContractMethod<[], [bigint], "view">;

  marketItemIdToMarketItem: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, string, bigint, boolean, boolean] & {
        marketItemId: bigint;
        amount: bigint;
        tokenAddress: string;
        seller: string;
        buyer: string;
        price: bigint;
        sold: boolean;
        canceled: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelMarketItem"
  ): TypedContractMethod<[marketItemId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarketForSale"
  ): TypedContractMethod<[marketItemId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "createMarketItem"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish, price: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fetchAvailableMarketItems"
  ): TypedContractMethod<
    [],
    [MemeCoinMarketplace.MarketItemStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getListingFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketItemIdToMarketItem"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, string, bigint, boolean, boolean] & {
        marketItemId: bigint;
        amount: bigint;
        tokenAddress: string;
        seller: string;
        buyer: string;
        price: bigint;
        sold: boolean;
        canceled: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
