/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MemeCoinmarketPlaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyToken"
      | "cancelListing"
      | "listingFee"
      | "marketItems"
      | "owner"
      | "renounceOwnership"
      | "sellTokens"
      | "transferOwnership"
      | "treasury"
      | "userListing"
      | "userListings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketItemCanceled"
      | "MarketItemCreated"
      | "MarketItemSold"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listingFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketItems",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellTokens",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userListing",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userListings",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listingFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userListings",
    data: BytesLike
  ): Result;
}

export namespace MarketItemCanceledEvent {
  export type InputTuple = [id: BigNumberish, seller: AddressLike];
  export type OutputTuple = [id: bigint, seller: string];
  export interface OutputObject {
    id: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketItemCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    seller: AddressLike,
    amount: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    seller: string,
    amount: bigint,
    price: bigint
  ];
  export interface OutputObject {
    id: bigint;
    seller: string;
    amount: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketItemSoldEvent {
  export type InputTuple = [
    id: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, buyer: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MemeCoinmarketPlace extends BaseContract {
  connect(runner?: ContractRunner | null): MemeCoinmarketPlace;
  waitForDeployment(): Promise<this>;

  interface: MemeCoinmarketPlaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyToken: TypedContractMethod<[_tokenId: BigNumberish], [void], "payable">;

  cancelListing: TypedContractMethod<
    [itemId: BigNumberish],
    [void],
    "nonpayable"
  >;

  listingFee: TypedContractMethod<[], [bigint], "view">;

  marketItems: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, string, bigint, boolean, boolean] & {
        id: bigint;
        amount: bigint;
        seller: string;
        buyer: string;
        tokenAddress: string;
        price: bigint;
        sold: boolean;
        canceled: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sellTokens: TypedContractMethod<
    [_tokenAddress: AddressLike, _amount: BigNumberish, _price: BigNumberish],
    [void],
    "payable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  userListing: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  userListings: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyToken"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "cancelListing"
  ): TypedContractMethod<[itemId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "listingFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketItems"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, string, bigint, boolean, boolean] & {
        id: bigint;
        amount: bigint;
        seller: string;
        buyer: string;
        tokenAddress: string;
        price: bigint;
        sold: boolean;
        canceled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellTokens"
  ): TypedContractMethod<
    [_tokenAddress: AddressLike, _amount: BigNumberish, _price: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userListing"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "userListings"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "MarketItemCanceled"
  ): TypedContractEvent<
    MarketItemCanceledEvent.InputTuple,
    MarketItemCanceledEvent.OutputTuple,
    MarketItemCanceledEvent.OutputObject
  >;
  getEvent(
    key: "MarketItemCreated"
  ): TypedContractEvent<
    MarketItemCreatedEvent.InputTuple,
    MarketItemCreatedEvent.OutputTuple,
    MarketItemCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketItemSold"
  ): TypedContractEvent<
    MarketItemSoldEvent.InputTuple,
    MarketItemSoldEvent.OutputTuple,
    MarketItemSoldEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "MarketItemCanceled(uint256,address)": TypedContractEvent<
      MarketItemCanceledEvent.InputTuple,
      MarketItemCanceledEvent.OutputTuple,
      MarketItemCanceledEvent.OutputObject
    >;
    MarketItemCanceled: TypedContractEvent<
      MarketItemCanceledEvent.InputTuple,
      MarketItemCanceledEvent.OutputTuple,
      MarketItemCanceledEvent.OutputObject
    >;

    "MarketItemCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      MarketItemCreatedEvent.InputTuple,
      MarketItemCreatedEvent.OutputTuple,
      MarketItemCreatedEvent.OutputObject
    >;
    MarketItemCreated: TypedContractEvent<
      MarketItemCreatedEvent.InputTuple,
      MarketItemCreatedEvent.OutputTuple,
      MarketItemCreatedEvent.OutputObject
    >;

    "MarketItemSold(uint256,address,uint256)": TypedContractEvent<
      MarketItemSoldEvent.InputTuple,
      MarketItemSoldEvent.OutputTuple,
      MarketItemSoldEvent.OutputObject
    >;
    MarketItemSold: TypedContractEvent<
      MarketItemSoldEvent.InputTuple,
      MarketItemSoldEvent.OutputTuple,
      MarketItemSoldEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
