/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketplaceSol from "./Marketplace.sol";
export type { marketplaceSol };
import type * as memecoinSol from "./Memecoin.sol";
export type { memecoinSol };
export type { Lock } from "./Lock";
export type { Treasury } from "./Treasury";
