/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Marketplace {
  export type MarketItemStruct = {
    marketItemId: BigNumberish;
    tokenId: BigNumberish;
    itemAddress: AddressLike;
    seller: AddressLike;
    buyer: AddressLike;
    price: BigNumberish;
    sold: boolean;
    canceled: boolean;
  };

  export type MarketItemStructOutput = [
    marketItemId: bigint,
    tokenId: bigint,
    itemAddress: string,
    seller: string,
    buyer: string,
    price: bigint,
    sold: boolean,
    canceled: boolean
  ] & {
    marketItemId: bigint;
    tokenId: bigint;
    itemAddress: string;
    seller: string;
    buyer: string;
    price: bigint;
    sold: boolean;
    canceled: boolean;
  };
}

export interface MarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createMarketItem"
      | "createMarketforsale"
      | "fetchAvailableMarketItems"
      | "getListingfees"
      | "marketItemIdToMarketItem"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createMarketItem",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarketforsale",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchAvailableMarketItems",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getListingfees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketItemIdToMarketItem",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createMarketItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarketforsale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchAvailableMarketItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getListingfees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketItemIdToMarketItem",
    data: BytesLike
  ): Result;
}

export interface Marketplace extends BaseContract {
  connect(runner?: ContractRunner | null): Marketplace;
  waitForDeployment(): Promise<this>;

  interface: MarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createMarketItem: TypedContractMethod<
    [tokenAddress: AddressLike, tokenId: BigNumberish, price: BigNumberish],
    [void],
    "payable"
  >;

  createMarketforsale: TypedContractMethod<
    [coinAddress: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;

  fetchAvailableMarketItems: TypedContractMethod<
    [],
    [Marketplace.MarketItemStructOutput[]],
    "view"
  >;

  getListingfees: TypedContractMethod<[], [bigint], "view">;

  marketItemIdToMarketItem: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, string, bigint, boolean, boolean] & {
        marketItemId: bigint;
        tokenId: bigint;
        itemAddress: string;
        seller: string;
        buyer: string;
        price: bigint;
        sold: boolean;
        canceled: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createMarketItem"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, tokenId: BigNumberish, price: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createMarketforsale"
  ): TypedContractMethod<
    [coinAddress: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fetchAvailableMarketItems"
  ): TypedContractMethod<[], [Marketplace.MarketItemStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getListingfees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketItemIdToMarketItem"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, string, bigint, boolean, boolean] & {
        marketItemId: bigint;
        tokenId: bigint;
        itemAddress: string;
        seller: string;
        buyer: string;
        price: bigint;
        sold: boolean;
        canceled: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
